# need 4 gpus

project: coconut
save_path: /home/user/coconut/hugface/saved_models/deepseek_qwen1.5b
name: gsm-coconut

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 1
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
load_model_path: /home/user/coconut/hugface/DeepSeek-R1-Distill-Qwen-1.5B-flats/last-checkpoint/rng_state.pth
seed: 0
resume: 3
bf16: True
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 4
num_epochs: 1
lr: !!float "1e-4"
weight_decay: 0.01
